databases:
  - name: Filecabinet
    ipAllowList: []
    databaseName: Filecabinet
    user: postgres

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Filecabinet
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false